export const DEGENESIS = {};
export const CLUSTER = {};

DEGENESIS.cultures = {
  borca: "DGNS.Borca",
  franka: "DGNS.Franka",
  purgare: "DGNS.Purgare",
  pollen: "DGNS.Pollen",
  africa: "DGNS.Africa",
  balkhan: "DGNS.Balkhan",
  hybrispania: "DGNS.Hybrispania",
};

DEGENESIS.cultureDescription = {
  borca: "DGNS.BorcaDescription",
  franka: "DGNS.FrankaDescription",
  purgare: "DGNS.PurgareDescription",
  pollen: "DGNS.PollenDescription",
  africa: "DGNS.AfricaDescription",
  balkhan: "DGNS.BalkhanDescription",
  hybrispania: "DGNS.HybrispaniaDescription",
};

DEGENESIS.cults = {
  spitalians: "DGNS.Spitalians",
  chroniclers: "DGNS.Chroniclers",
  hellvetics: "DGNS.Hellvetics",
  judges: "DGNS.Judges",
  clanners: "DGNS.Clanners",
  scrappers: "DGNS.Scrappers",
  neolibyans: "DGNS.Neolibyans",
  scourgers: "DGNS.Scourgers",
  anubians: "DGNS.Anubians",
  jehammedans: "DGNS.Jehammedans",
  apocalyptics: "DGNS.Apocalyptics",
  anabaptists: "DGNS.Anabaptists",
  palers: "DGNS.Palers",
};

DEGENESIS.cultDescription = {
  spitalians: "DGNS.SpitaliansDescription",
  chroniclers: "DGNS.ChroniclersDescription",
  hellvetics: "DGNS.HellveticsDescription",
  judges: "DGNS.JudgesDescription",
  clanners: "DGNS.ClannersDescription",
  scrappers: "DGNS.ScrappersDescription",
  neolibyans: "DGNS.NeolibyansDescription",
  scourgers: "DGNS.ScourgersDescription",
  anubians: "DGNS.AnubiansDescription",
  jehammedans: "DGNS.JehammedansDescription",
  apocalyptics: "DGNS.ApocalypticsDescription",
  anabaptists: "DGNS.AnabaptistsDescription",
  palers: "DGNS.PalersDescription",
};

DEGENESIS.concepts = {
  adventurer: "DGNS.Adventurer",
  creator: "DGNS.Creator",
  mentor: "DGNS.Mentor",
  martyr: "DGNS.Martyr",
  ruler: "DGNS.Ruler",
  seeker: "DGNS.Seeker",
  healer: "DGNS.Healer",
  traditionalist: "DGNS.Traditionalist",
  mediator: "DGNS.Mediator",
  hermit: "DGNS.Hermit",
  heretic: "DGNS.Heretic",
  conqueror: "DGNS.Conqueror",
  abomination: "DGNS.Abomination",
  destroyer: "DGNS.Destroyer",
  chosen: "DGNS.Chosen",
  defiler: "DGNS.Defiler",
  protector: "DGNS.Protector",
  visionary: "DGNS.Visionary",
  zealot: "DGNS.Zealot",
  disciple: "DGNS.Disciple",
  righteous: "DGNS.Righteous",
  traveler: "DGNS.Traveler",
};

DEGENESIS.conceptDescription = {
  adventurer: "DGNS.AdventurerDescription",
  creator: "DGNS.CreatorDescription",
  mentor: "DGNS.MentorDescription",
  martyr: "DGNS.MartyrDescription",
  ruler: "DGNS.RulerDescription",
  seeker: "DGNS.SeekerDescription",
  healer: "DGNS.HealerDescription",
  traditionalist: "DGNS.TraditionalistDescription",
  mediator: "DGNS.MediatorDescription",
  hermit: "DGNS.HermitDescription",
  heretic: "DGNS.HereticDescription",
  conqueror: "DGNS.ConquerorDescription",
  abomination: "DGNS.AbominationDescription",
  destroyer: "DGNS.DestroyerDescription",
  chosen: "DGNS.ChosenDescription",
  defiler: "DGNS.DefilerDescription",
  protector: "DGNS.ProtectorDescription",
  visionary: "DGNS.VisionaryDescription",
  zealot: "DGNS.ZealotDescription",
  disciple: "DGNS.DiscipleDescription",
  righteous: "DGNS.RighteousDescription",
  traveler: "DGNS.TravelerDescription",
};

DEGENESIS.raptures = {
  biokinetics: "DGNS.Biokinetics",
  dushani: "DGNS.Dushani",
  leviathans: "DGNS.Leviathans",
  pheromancers: "DGNS.Pheromancers",
  pregnoctics: "DGNS.Pregnoctics",
  psychokinetics: "DGNS.Psychokinetics",
};

DEGENESIS.attributes = {
  body: "DGNS.Body",
  agility: "DGNS.Agility",
  charisma: "DGNS.Charisma",
  intellect: "DGNS.Intellect",
  psyche: "DGNS.Psyche",
  instinct: "DGNS.Instinct",
};

DEGENESIS.attributeAbbrev = {
  body: "DGNS.BodyAbbrev",
  agility: "DGNS.AgilityAbbrev",
  charisma: "DGNS.CharismaAbbrev",
  intellect: "DGNS.IntellectAbbrev",
  psyche: "DGNS.PsycheAbbrev",
  instinct: "DGNS.InstinctAbbrev",
};

DEGENESIS.attributeType = {
  body: "primal",
  agility: "focus",
  charisma: "primal",
  intellect: "focus",
  psyche: "focus",
  instinct: "primal",
};

DEGENESIS.skills = {
  athletics: "DGNS.Athletics",
  brawl: "DGNS.Brawl",
  force: "DGNS.Force",
  melee: "DGNS.Melee",
  stamina: "DGNS.Stamina",
  toughness: "DGNS.Toughness",
  crafting: "DGNS.Crafting",
  dexterity: "DGNS.Dexterity",
  navigation: "DGNS.Navigation",
  mobility: "DGNS.Mobility",
  projectiles: "DGNS.Projectiles",
  stealth: "DGNS.Stealth",
  arts: "DGNS.Arts",
  conduct: "DGNS.Conduct",
  expression: "DGNS.Expression",
  leadership: "DGNS.Leadership",
  negotiation: "DGNS.Negotiation",
  seduction: "DGNS.Seduction",
  artifact: "DGNS.ArtifactLore",
  engineering: "DGNS.Engineering",
  focus: "DGNS.Focus",
  legends: "DGNS.Legends",
  medicine: "DGNS.Medicine",
  science: "DGNS.Science",
  cunning: "DGNS.Cunning",
  deception: "DGNS.Deception",
  domination: "DGNS.Domination",
  faith: "DGNS.Faith",
  reaction: "DGNS.Reaction",
  willpower: "DGNS.Willpower",
  empathy: "DGNS.Empathy",
  orienteering: "DGNS.Orienteering",
  perception: "DGNS.Perception",
  primal: "DGNS.Primal",
  survival: "DGNS.Survival",
  taming: "DGNS.Taming",
};

DEGENESIS.skillAttributes = {
  athletics: "body",
  brawl: "body",
  force: "body",
  melee: "body",
  stamina: "body",
  toughness: "body",
  crafting: "agility",
  dexterity: "agility",
  navigation: "agility",
  mobility: "agility",
  projectiles: "agility",
  stealth: "agility",
  arts: "charisma",
  conduct: "charisma",
  expression: "charisma",
  leadership: "charisma",
  negotiation: "charisma",
  seduction: "charisma",
  artifact: "intellect",
  engineering: "intellect",
  focus: "intellect",
  legends: "intellect",
  medicine: "intellect",
  science: "intellect",
  cunning: "psyche",
  deception: "psyche",
  domination: "psyche",
  faith: "psyche",
  reaction: "psyche",
  willpower: "psyche",
  empathy: "instinct",
  orienteering: "instinct",
  perception: "instinct",
  primal: "instinct",
  survival: "instinct",
  taming: "instinct",
};

DEGENESIS.fightRolls = {
  dodge: "mobility",
  initiative: "reaction",
  mentalDefense: "willpower",
};

DEGENESIS.diceRolls = {
  initiative: "DGNS.Initiative",
};

DEGENESIS.modifyTypes = {
  D: "D",
  S: "S",
  T: "T",
};

DEGENESIS.modifyActions = {
  initiative: "DGNS.Initiative",
  dodge: "DGNS.Dodge",
  movement: "DGNS.Movement",
  armor: "DGNS.Armor",
  action: "DGNS.Action",
  attack: "DGNS.Attack",
  damage: "DGNS.Damage",
  a_defense: "DGNS.ActiveDefense",
  p_defense: "DGNS.PassiveDefense",
  mentalDefense: "DGNS.MentalDef",
};

DEGENESIS.noType = ["movement", "armor", "damage", "p_defense"];

DEGENESIS.weaponGroups = {
  brawl: "DGNS.Brawl",
  armedMelee: "DGNS.ArmedMelee",
  thrown: "DGNS.ThrownWeapons",
  projectiles: "DGNS.Projectiles",
  handguns: "DGNS.Handguns",
  rifles: "DGNS.Rifles",
  heavy: "DGNS.HeavyWeapons",
  explosives: "DGNS.Explosives",
  sonic: "DGNS.SonicWeapons",
};

DEGENESIS.attackGroups = {
  closeQuarter: "DGNS.CloseQuarter",
  ranged: "DGNS.Ranged",
};

DEGENESIS.defenseGroups = {
  passive: "DGNS.DefensePassive",
  meleeActive: "DGNS.DefenseMeleeActive",
  rangedActive: "DGNS.DefenseRangedActive",
  mental: "DGNS.DefenseMental",
};

DEGENESIS.equipmentGroups = {
  "getting food": "DGNS.GettingFood",
  traps: "DGNS.Traps",
  sourcesOfLight: "DGNS.SourceOfLightFire",
  orienteeringTracking: "DGNS.OrienteeringTracking",
  climbing: "DGNS.Climbing",
  overnight: "DGNS.Overnight",
  inTheShadows: "DGNS.InTheShadows",
  gasMasks: "DGNS.GazMasks",
  survivalGear: "DGNS.SurvivalGear",
  technology: "DGNS.Technology",
  sunDiscs: "DGNS.SunDiscs",
  chroniclerSuitModules: "DGNS.ChroniclerSuitModules",
  heavyDutyModules: "DGNS.HeavyDutyModules",
  communication: "DGNS.Communication",
  energyManagement: "DGNS.EnergyManagement",
  medicalEquipment: "DGNS.MedicalEquipment",
  pharmaceutics: "DGNS.Pharmaceutics",
  elysianOils: "DGNS.ElysianOils",
  psychonauticRemains: "DGNS.PsychonauticRemains",
  huntingPsychonauts: "DGNS.HuntingPsychonauts",
  commonPrimalism: "DGNS.CommonPrimalism",
  talismansInsignia: "DGNS.TalismansInsignia",
  scrap: "DGNS.Scrap",
  other: "DGNS.Other",
  transportation: "DGNS.Transportation",
};

DEGENESIS.weaponGroupSkill = {
  brawl: "brawl",
  armedMelee: "melee",
  thrown: "projectiles",
  projectiles: "projectiles",
  handguns: "projectiles",
  rifles: "projectiles",
  heavy: "projectiles",
  explosives: "projectiles",
  sonic: "engineering",
};

(DEGENESIS.weaponQualities = {
  areaDamage: "DGNS.AreaDamage",
  armorPiercing: "DGNS.Armorpiercing",
  biometricallyEncoded: "DGNS.BiometricallyEncoded",
  blunt: "DGNS.Blunt",
  camo: "DGNS.WeaponCamo",
  cutting: "DGNS.Cutting",
  cloud: "DGNS.Cloud",
  dazed: "DGNS.Dazed",
  deviation: "DGNS.Deviation",
  doubleBarreled: "DGNS.DoubleBarreled",
  entangled: "DGNS.Entangled",
  explosive: "DGNS.Explosive",
  fatal: "DGNS.Fatal",
  fireHazardous: "DGNS.FireHazardous",
  fragile: "DGNS.Fragile",
  impact: "DGNS.Impact",
  jamming: "DGNS.Jamming",
  muzzleLoader: "DGNS.MuzzleLoader",
  outOfControl: "DGNS.OutOfControl",
  piercing: "DGNS.Piercing",
  salvoes: "DGNS.Salvoes",
  scatter: "DGNS.Scatter",
  sensitive: "DGNS.Sensitive",
  smoothRunning: "DGNS.SmoothRunning",
  special: "DGNS.Special",
  specialDamage: "DGNS.SpecialDamage",
  standard: "DGNS.Standard",
  talisman: "DGNS.Talisman",
  terrifying: "DGNS.WeaponTerrifying",
  thunderStrike: "DGNS.ThunderStrike",
  extendedReload: "DGNS.ExtendedReload",
  gruesome: "DGNS.Gruesome",
  stun: "DGNS.Stun",
  panic: "DGNS.Panic",
  singleLoader: "DGNS.SingleLoader",
}),
  (DEGENESIS.agentQualities = {
    poisoned: "POISONED",
    attractant: "ATTRACTANT",
    narcotic: "NARCOTIC",
    pseudoDesporeing: "PSEUDO DESPOREING",
  }),
  (DEGENESIS.armorQualities = {
    respected: "DGNS.Respected",
    firstImpression: "DGNS.FirstImpression",
    fireResistant: "DGNS.FireResistant",
    terrifying: "DGNS.ArmorTerrifying",
    camo: "DGNS.ArmorCamo",
    unstable: "DGNS.Unstable",
    insulated: "DGNS.Insulated",
    bulletproof: "DGNS.Bulletproof",
    massive: "DGNS.Massive",
    brittle: "DGNS.Brittle",
    sealed: "DGNS.Sealed",
    special: "DGNS.ArmorSpecial",
  }),
  (DEGENESIS.shieldQualities = { special: "DGNS.Special" }),
  (DEGENESIS.attackQualities = {
    areaDamage: "DGNS.AreaDamage",
    armorPiercing: "DGNS.Armorpiercing",
    biometricallyEncoded: "DGNS.BiometricallyEncoded",
    blunt: "DGNS.Blunt",
    camo: "DGNS.WeaponCamo",
    cutting: "DGNS.Cutting",
    cloud: "DGNS.Cloud",
    dazed: "DGNS.Dazed",
    deviation: "DGNS.Deviation",
    doubleBarreled: "DGNS.DoubleBarreled",
    entangled: "DGNS.Entangled",
    explosive: "DGNS.Explosive",
    fatal: "DGNS.Fatal",
    fireHazardous: "DGNS.FireHazardous",
    fragile: "DGNS.Fragile",
    impact: "DGNS.Impact",
    jamming: "DGNS.Jamming",
    muzzleLoader: "DGNS.MuzzleLoader",
    outOfControl: "DGNS.OutOfControl",
    piercing: "DGNS.Piercing",
    salvoes: "DGNS.Salvoes",
    scatter: "DGNS.Scatter",
    sensitive: "DGNS.Sensitive",
    smoothRunning: "DGNS.SmoothRunning",
    special: "DGNS.Special",
    specialDamage: "DGNS.SpecialDamage",
    standard: "DGNS.Standard",
    talisman: "DGNS.Talisman",
    terrifying: "DGNS.WeaponTerrifying",
    thunderStrike: "DGNS.ThunderStrike",
    extendedReload: "DGNS.ExtendedReload",
    gruesome: "DGNS.Gruesome",
    stun: "DGNS.Stun",
    panic: "DGNS.Panic",
    singleLoader: "DGNS.SingleLoader",
  }),
  (DEGENESIS.defenseQualities = { special: "DGNS.Special" }),
  (DEGENESIS.weaponQualitiesValues = {
    areaDamage: ["angle"],
    armorPiercing: [],
    biometricallyEncoded: ["difficulty"],
    blunt: [],
    camo: ["difficulty"],
    cloud: ["radius", "amountOfTime"],
    cutting: ["trigger", "damage"],
    dazed: ["egoDamage"],
    deviation: [],
    doubleBarreled: [],
    entangled: ["movementPenalty"],
    explosive: [],
    fatal: [],
    fireHazardous: [],
    fragile: [],
    impact: ["trigger"],
    jamming: [],
    muzzleLoader: [],
    outOfControl: ["difficulty"],
    piercing: ["armorRating"],
    salvoes: ["rounds"],
    scatter: [],
    sensitive: [],
    smoothRunning: ["trigger"],
    special: [],
    specialDamage: ["enemyType", "damage"],
    standard: ["bonus"],
    talisman: ["bonus"],
    terrifying: ["difficulty"],
    thunderStrike: [],
    extendedReload: ["time"],
    gruesome: ["rating"],
    stun: ["rating"],
    panic: ["rating"],
    singleLoader: ["rounds"],
  }),
  (DEGENESIS.agentQualitiesValues = {
    poisoned: ["potency", "effect", "duration"],
    attractant: ["target"],
    narcotic: ["potency", "damage"],
    pseudoDesporeing: ["desporeing", "duration"],
  }),
  (DEGENESIS.armorQualitiesValues = {
    respected: ["targetGroup", "bonusDice"],
    firstImpression: ["bonus"],
    fireResistant: ["armor"],
    terrifying: ["difficulty"],
    camo: ["difficulty"],
    unstable: ["criticalDamageRating"],
    insulated: [],
    bulletproof: ["armor"],
    massive: ["armor"],
    brittle: ["criticalDamageRating"],
    sealed: ["bonusSuccesses"],
    special: [],
  }),
  (DEGENESIS.shieldQualitiesValues = { special: [] }),
  (DEGENESIS.attackQualitiesValues = {
    areaDamage: ["angle"],
    armorPiercing: [],
    biometricallyEncoded: ["difficulty"],
    blunt: [],
    camo: ["difficulty"],
    cloud: ["radius", "amountOfTime"],
    cutting: ["trigger", "damage"],
    dazed: ["egoDamage"],
    deviation: [],
    doubleBarreled: [],
    entangled: ["movementPenalty"],
    explosive: [],
    fatal: [],
    fireHazardous: [],
    fragile: [],
    impact: ["trigger"],
    jamming: [],
    muzzleLoader: [],
    outOfControl: ["difficulty"],
    piercing: ["armorRating"],
    salvoes: ["rounds"],
    scatter: [],
    sensitive: [],
    smoothRunning: ["trigger"],
    special: [],
    specialDamage: ["enemyType", "damage"],
    standard: ["bonus"],
    talisman: ["bonus"],
    terrifying: ["difficulty"],
    thunderStrike: [],
    extendedReload: ["time"],
    gruesome: ["rating"],
    stun: ["rating"],
    panic: ["rating"],
    singleLoader: ["rounds"],
  }),
  (DEGENESIS.defenseQualitiesValues = { special: [] }),
  (DEGENESIS.qualityValues = {
    angle: "DGNS.Angle",
    difficulty: "DGNS.Difficulty",
    time: "DGNS.Time",
    damage: "DGNS.QualityDamage",
    amountOfTime: "DGNS.AmountOfTime",
    movementPenalty: "DGNS.MovementPenalty",
    egoDamage: "DGNS.EgoDamage",
    radius: "DGNS.Radius",
    penalty: "DGNS.Penalty",
    trigger: "DGNS.Trigger",
    bonus: "DGNS.Bonus",
    enemyType: "DGNS.EnemyType",
    rating: "DGNS.Rating",
    armorRating: "DGNS.ArmorRating",
    rounds: "DGNS.NumberOfRounds",
    potency: "DGNS.Potency",
    effect: "DGNS.QualityEffect",
    target: "DGNS.Target",
    desporeing: "DGNS.Desporeing",
    duration: "DGNS.Duration",
    targetGroup: "DGNS.TargetGroup",
    bonusDice: "DGNS.BonusDice",
    armor: "DGNS.QualityArmor",
    criticalDamageRating: "DGNS.CriticalDamageRating",
    bonusSuccesses: "DGNS.BonusSuccesses",
  });

(DEGENESIS.weaponQualityDescription = {
  areaDamage: "DGNS.AreaDamageDescription",
  armorPiercing: "DGNS.ArmorpiercingDescription",
  biometricallyEncoded: "DGNS.BiometricallyEncodedDescription",
  blunt: "DGNS.BluntDescription",
  camo: "DGNS.WeaponCamoDescription",
  cloud: "DGNS.CloudDescription",
  dazed: "DGNS.DazedDescription",
  deviation: "DGNS.DeviationDescription",
  doubleBarreled: "DGNS.DoubleBarreledDescription",
  entangled: "DGNS.EntangledDescription",
  explosive: "DGNS.ExplosiveDescription",
  fatal: "DGNS.FatalDescription",
  fireHazardous: "DGNS.FireHazardousDescription",
  fragile: "DGNS.FragileDescription",
  impact: "DGNS.ImpactDescription",
  jamming: "DGNS.JammingDescription",
  muzzleLoader: "DGNS.MuzzleLoaderDescription",
  outOfControl: "DGNS.OutOfControlDescription",
  piercing: "DGNS.PiercingDescription",
  salvoes: "DGNS.SalvoesDescription",
  scatter: "DGNS.ScatterDescription",
  sensitive: "DGNS.SensitiveDescription",
  smoothRunning: "DGNS.SmoothRunningDescription",
  special: "DGNS.SpecialDescription",
  specialDamage: "DGNS.SpecialDamageDescription",
  standard: "DGNS.StandardDescription",
  talisman: "DGNS.TalismanDescription",
  terrifying: "DGNS.WeaponTerrifyingDescription",
  thunderStrike: "DGNS.ThunderStrikeDescription",
  extendedReload: "DGNS.ExtendedReloadDescription",
  gruesome: "DGNS.GruesomeDescription",
  stun: "DGNS.StunDescription",
  panic: "DGNS.PanicDescription",
  singleLoader: "DGNS.SingleLoaderDescription",
  cutting: "DGNS.CuttingDescription",
}),
  (DEGENESIS.agentQualityDescription = {
    poisoned: "DGNS.PoisonedDescription",
    attractant: "DGNS.AttractantDescription",
    narcotic: "DGNS.NarcoticDescription",
    pseudoDesporeing: "DGNS.PseudodesporeingDescription",
  }),
  (DEGENESIS.armorQualityDescription = {
    respected: "DGNS.RespectedDescription",
    firstImpression: "DGNS.FirstImpressionDescription",
    fireResistant: "DGNS.FireResistantDescription",
    terrifying: "DGNS.ArmorTerrifyingDescription",
    camo: "DGNS.ArmorCamoDescription",
    unstable: "DGNS.UnstableDescription",
    insulated: "DGNS.InsulatedDescription",
    bulletproof: "DGNS.BulletProofDescription",
    massive: "DGNS.MassiveDescription",
    brittle: "DGNS.BrittleDescription",
    sealed: "DGNS.SealedDescription",
    special: "DGNS.SpecialDescription",
  }),
  (DEGENESIS.shieldQualityDescription = {
    special: "DGNS.SpecialDescription",
  }),
  (DEGENESIS.attackQualityDescription = {
    areaDamage: "DGNS.AreaDamageDescription",
    armorPiercing: "DGNS.ArmorpiercingDescription",
    biometricallyEncoded: "DGNS.BiometricallyEncodedDescription",
    blunt: "DGNS.BluntDescription",
    camo: "DGNS.WeaponCamoDescription",
    cloud: "DGNS.CloudDescription",
    dazed: "DGNS.DazedDescription",
    deviation: "DGNS.DeviationDescription",
    doubleBarreled: "DGNS.DoubleBarreledDescription",
    entangled: "DGNS.EntangledDescription",
    explosive: "DGNS.ExplosiveDescription",
    fatal: "DGNS.FatalDescription",
    fireHazardous: "DGNS.FireHazardousDescription",
    fragile: "DGNS.FragileDescription",
    impact: "DGNS.ImpactDescription",
    jamming: "DGNS.JammingDescription",
    muzzleLoader: "DGNS.MuzzleLoaderDescription",
    outOfControl: "DGNS.OutOfControlDescription",
    piercing: "DGNS.PiercingDescription",
    salvoes: "DGNS.SalvoesDescription",
    scatter: "DGNS.ScatterDescription",
    sensitive: "DGNS.SensitiveDescription",
    smoothRunning: "DGNS.SmoothRunningDescription",
    special: "DGNS.SpecialDescription",
    specialDamage: "DGNS.SpecialDamageDescription",
    standard: "DGNS.StandardDescription",
    talisman: "DGNS.TalismanDescription",
    terrifying: "DGNS.WeaponTerrifyingDescription",
    thunderStrike: "DGNS.ThunderStrikeDescription",
    extendedReload: "DGNS.ExtendedReloadDescription",
    gruesome: "DGNS.GruesomeDescription",
    stun: "DGNS.StunDescription",
    panic: "DGNS.PanicDescription",
    singleLoader: "DGNS.SingleLoaderDescription",
    cutting: "DGNS.CuttingDescription",
  }),
  (DEGENESIS.defenseQualityDescription = {
    special: "DGNS.SpecialDescription",
  }),
  (DEGENESIS.damageTypes = {
    fleshwounds: "DGNS.Fleshwounds",
    ego: "DGNS.Ego",
    trauma: "DGNS.Trauma",
  });

DEGENESIS.damageModifiers = {
  F: { blueprint: "+F", calculate: (force, triggers) => force },
  F2: {
    blueprint: "+F/2",
    calculate: (force, triggers) => Math.ceil(force / 2),
  },
  F3: {
    blueprint: "+F/3",
    calculate: (force, triggers) => Math.ceil(force / 3),
  },
  F4: {
    blueprint: "+F/4",
    calculate: (force, triggers) => Math.ceil(force / 4),
  },
  T: { blueprint: "+T", calculate: (force, triggers) => triggers },
  D2: {
    blueprint: "+1D/2",
    calculate: (force, triggers) =>
      Math.ceil(new Die({ faces: 6, number: 1 }).evaluate().total / 2),
  },
  D: {
    blueprint: "+1D",
    calculate: (force, triggers) =>
      new Die({ faces: 6, number: 1 }).evaluate().total,
  },
  "2D": {
    blueprint: "+2D",
    calculate: (force, triggers) =>
      new Die({ faces: 6, number: 2 }).evaluate().total,
  },
};

DEGENESIS.damageModifiersFromHell = {
  T: { blueprint: "+T", calculate: (triggers) => triggers },
  D2: {
    blueprint: "+1D/2",
    calculate: (triggers) =>
      Math.ceil(new Die({ faces: 6, number: 1 }).evaluate().total / 2),
  },
  D: {
    blueprint: "+1D",
    calculate: (triggers) => new Die({ faces: 6, number: 1 }).evaluate().total,
  },
  "2D": {
    blueprint: "+2D",
    calculate: (triggers) => new Die({ faces: 6, number: 2 }).evaluate().total,
  },
};

DEGENESIS.techValues = {
  1: "I",
  2: "II",
  3: "III",
  4: "IV",
  5: "V",
  6: "VI",
};

DEGENESIS.rollResults = {
  success: "DGNS.Success",
  failure: "DGNS.Failure",
  botch: "DGNS.Botch",
};

DEGENESIS.calibers = {
  "50gl": "TYPES.Ammo.50gl",
  357: "TYPES.Ammo.357",
  44: "TYPES.Ammo.44",
  "410sh": "TYPES.Ammo.410sh",
  "410sl": "TYPES.Ammo.410sl",
  556: "TYPES.Ammo.556",
  jacket: "TYPES.Ammo.jacket",
  hollowPoint: "TYPES.Ammo.hollowPoint",
  flechette: "TYPES.Ammo.flechette",
  "46x30": "TYPES.Ammo.46x30",
  "9mm": "TYPES.Ammo.9mm",
  "5x30": "TYPES.Ammo.5x30",
  762: "TYPES.Ammo.762",
  14: "TYPES.Ammo.14",
  buckshot: "TYPES.Ammo.buckshot",
  rifleBarrel: "TYPES.Ammo.rifleBarrel",
  cartridge: "TYPES.Ammo.cartridge",
  grenade: "TYPES.Ammo.grenade",
  missile: "TYPES.Ammo.missile",
  fragger: "TYPES.Ammo.fragger",
  blackpowder: "TYPES.Ammo.blackpowder",
  leadbullet: "TYPES.Ammo.leadbullet",
  Ecube: "TYPES.Ammo.Ecube",
  arrow: "TYPES.Ammo.arrow",
  bolt: "TYPES.Ammo.bolt",
  petro: "TYPES.Ammo.petro",
  harpoon: "TYPES.Ammo.harpoon",
  nail: "TYPES.Ammo.nail",
  coal: "TYPES.Ammo.coal",
  boltcoal: "TYPES.Ammo.boltcoal",
  special: "TYPES.Ammo.special",
};

DEGENESIS.systemItems = {
  spentEgoActionModifier: {
    type: "modifier",
    data: {
      action: "action",
      type: "D",
    },
  },
  spentSporeActionModifier: {
    type: "modifier",
    data: {
      action: "action",
      type: "D",
    },
  },
};

DEGENESIS.transportationEncumbranceCalculation = {
  wholeReduction: (items, reductionValue) => {
    let totalEnc = items.reduce((a, b) => a + (b.encumbrance || 0), 0);
    totalEnc -= reductionValue;
    if (totalEnc < 0) totalEnc = 0;
    return totalEnc;
  },
  eachReduction: (items, reductionValue) => {
    let totalEnc = items.reduce((a, b) => {
      let enc = (b.encumbrance * b.quantity || 0) - reductionValue * b.quantity;
      if (enc < 0) enc = 0;
      return a + enc;
    }, 0);
    if (totalEnc < 0) totalEnc = 0;
    return totalEnc;
  },
};

DEGENESIS.transportationEncumbranceModes = {
  wholeReduction: "DGNS.WholeReduction",
  eachReduction: "DGNS.EachReduction",
};

CLUSTER.genders = {
  male: "Male",
  female: "Female",
  neutral: "Neutral",
};

CLUSTER.randomizerOptions = {
  antagonists: "Antagonists",
  bygoneCompanyName: "Bygone Company Name",
  prophecyDreams: "Cryptic Names for Propechies or Dreams",
  foodDrink: "Food and Drinks",
  hallucinations: "Hallucinations",
  patrons: "Inn and Bar Patrons",
  jobs: "Jobs",
  obsession: "NPC Obsessions",
  objects: "Objects",
  shops: "Shops and Stalls",
  ruin: "This ruin is based on...",
  travelComplications: "Travel Complications",
};

CLUSTER.techLevels = {
  1: "I",
  2: "II",
  3: "III",
  4: "IV",
  5: "V",
};
